// <auto-generated />
namespace FunBet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddIso2ToTeam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIso2ToTeam));
        
        string IMigrationMetadata.Id
        {
            get { return "201806030026022_AddIso2ToTeam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
